name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - BoogieMonster1O1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: ver
    attributes:
      label: Mod Version
      description: What version of Dimensional Doors are you using?
      placeholder: "5.0.2"
    validations:
      required: false
  - type: dropdown
    id: mcver
    attributes:
      label: What versions of Minecraft does this issue happen on?
      multiple: true
      options:
        - "1.12.2"
        - "1.19.3"
  - type: textarea
    id: logs
    attributes:
      label: Log
      description: Please copy and paste any relevant log output, or your full latest.log
      render: shell
