name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - BoogieMonster1O1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
name: Suggestion
description: Make a suggestion
title: "[Suggestion]: "
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: This suggestion is unique
    options:
    - label: I have searched the issue tracker and did not find an issue describing my suggestion
      required: true
- type: textarea
  attributes:
    label: Use the editor below to elaborate.
