modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "dimdoors"
version = "${version}"
displayName = "DimensionalDoors"
authors = "StevenRS11, SenseiKiwi, Zixiken, Waterpicker, Robijnvogel, ZombieHDGaming, Runemoro"
description = '''
Bend and twist reality, creating rifts, pocket dimensions, and much more
'''
#logoFile = ""

[[dependencies.dimdoors]]
modId = "neoforge"
mandatory = true
versionRange = "[21.+,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dimdoors]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"